project_id = "kzxusjxvgrtchjrzwrzd"

[functions.weather]
verify_jwt = false

[functions.air-quality]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.chennai-status-updater]
verify_jwt = false

[functions.weather-forecast]
verify_jwt = false
